model:
    target: enhancing.modules.stage1.vitvqgan.ViTVQ
    params:
        image_key: image
        hparams:
            image_size: 32
            patch_size: 8
            dim: 768
            depth: 12
            heads: 12
            mlp_dim: 3072
        qparams:
            embed_dim: 32
            n_embed: 8192
        loss:
            target: enhancing.losses.vqperceptual.VQLPIPSWithDiscriminator
            params:
                loglaplace_weight: 0.0
                loggaussian_weight: 1.0
                perceptual_weight: 0.1
                adversarial_weight: 0.1
                disc_params:
                    size: 32

dataset:
    target: enhancing.dataloader.DataModuleFromConfig
    params:
        batch_size: 8
        num_workers: 4
        train:
            target: enhancing.dataloader.classimage.ClassImageTrain
            params:
                root: /home/brans/repos/spaces_dataset-master/data/800/scene_066/cam_04/
                resolution: 32

        validation:
            target: enhancing.dataloader.classimage.ClassImageValidation
            params:
                root: /home/brans/repos/spaces_dataset-master/data/800/scene_066/cam_04/
                resolution: 32